version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static-backend/
      - media_value:/var/html/media/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: ../morec
      dockerfile: ../morec/Dockerfile.backend
    env_file: devops.env
    ports:
      - "8000:8000"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - postgres_db

  postgres_db:
    image: "postgres:13.4-alpine"
    ports:
      - "5432:5432"
    env_file: devops.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_value:
  media_value: